In [213]:
import numpy as np

In [214]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


* 运算方法 + - ** sin cos tan等

In [215]:
a+b 

array([10, 21, 32, 43])

In [216]:
a-b

array([10, 19, 28, 37])

In [217]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [218]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [219]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493])

* numpy矩阵的直接判断输出

In [220]:
print(b<3)
b == 3

[ True  True  True False]


array([False, False, False,  True])

In [221]:
a = np.array([  [1,1],[0,1]  ])
b = np.arange(4).reshape(2,2)
a,b

(array([[1, 1],
        [0, 1]]),
 array([[0, 1],
        [2, 3]]))

### 矩阵之间的乘法运算


In [222]:
c1=a*b
c1

array([[0, 1],
       [0, 3]])

* ↑对应位置上的数相乘↑

In [223]:
c2=np.dot(a,b) # 写法1
c3=a.dot(b)  #  写法2
c2,c3

(array([[2, 4],
        [2, 3]]),
 array([[2, 4],
        [2, 3]]))

* ↑矩阵的乘法相乘↑

In [224]:
d= np.random.random((2,4))
d

array([[0.13902782, 0.2297967 , 0.97912315, 0.73103525],
       [0.58173352, 0.58677922, 0.16740447, 0.21492644]])

* 从0-1随机出数字组成一个2x4的矩阵

In [225]:
e=np.array([
    [0,1,2,3],
    [1,2,3,4]
])


* 求和 axis=0--分列求和  axis=1--分行求和

In [226]:
print(np.sum(e))
print(np.sum(e,axis=0))
print(np.sum(e,axis=1))

16
[1 3 5 7]
[ 6 10]


* 求最大   axis=0--分列求最大   axis=1--分行最大 

In [227]:
print(np.max(e))
print(np.max(e,axis=0))
print(np.max(e,axis=1))

4
[1 2 3 4]
[3 4]


* 求最小 axis=0--分列求最小  axis=1--分行求最小

In [228]:
print(np.min(e))
print(np.min(e,axis=0))
print(np.min(e,axis=1))

0
[0 1 2 3]
[0 1]


------------------------------------------------------------------
***

In [229]:
A=np.arange(14,2,-1).reshape(3,4)
A

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

* 求最大最小值的索引下标

In [230]:
np.argmin(A)  ,   np.argmax(A)

(11, 0)

* 求矩阵平均值

In [231]:
np.mean(A), np.average(A), A.mean()     

(8.5, 8.5, 8.5)

* 求中位数

In [232]:
np.median(A)

8.5

* 累加序列

In [233]:
 np.cumsum(A)

array([ 14,  27,  39,  50,  60,  69,  77,  84,  90,  95,  99, 102],
      dtype=int32)

* 累差序列        3x4会变成3x3

In [234]:
np.diff(A)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

* 非零数 序列 得到的非零数字的 行下标 和 列下标

In [235]:
np.nonzero(A)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

+ 逐行排序

In [236]:
np.sort(A)

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

+ 矩阵转置

In [237]:
np.transpose(A)    ,    A.T

(array([[14, 10,  6],
        [13,  9,  5],
        [12,  8,  4],
        [11,  7,  3]]),
 array([[14, 10,  6],
        [13,  9,  5],
        [12,  8,  4],
        [11,  7,  3]]))

+ 截取 （所有小于5的数都等于5；所有大于9的数都等于9）

In [238]:
np.clip(A,5,9)

array([[9, 9, 9, 9],
       [9, 9, 8, 7],
       [6, 5, 5, 5]])

+ axis    0→列 1→行

In [239]:
np.mean(A,axis=0) # 对列

array([10.,  9.,  8.,  7.])

In [240]:
np.mean(A,axis=1) # 对行

array([12.5,  8.5,  4.5])