In [30]:
import numpy as np

In [31]:
a=np.arange(3,15).reshape(3,4)
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

+ np[行][列] np[行，列]

In [32]:
a[1][1], a[1,1]

(8, 8)

+ [:]表示这一条的所有数

In [33]:
a[1][:], a[1,:]

(array([ 7,  8,  9, 10]), array([ 7,  8,  9, 10]))

+ 可以定位之后就可以写for循环了
        # 迭代行

In [34]:
for row in a:  # 迭代行
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


        # 迭代列

In [35]:
for column in a.T:  # 迭代列
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


## 迭代器 a.flat    迭代值 a.flatten()

In [36]:
print(a.flat)
print(a.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [37]:
for i in a.flat:
    print(i,end=' ')
print()
print('---------------迭代器与迭代值的用法-----------------')
for i in a.flatten():
    print(i,end=' ')

3 4 5 6 7 8 9 10 11 12 13 14 
---------------迭代器与迭代值的用法-----------------
3 4 5 6 7 8 9 10 11 12 13 14 