In [22]:
import numpy as np

In [23]:
A=np.array([1,1,1])
B=np.array([2,2,2])

+ 上下合并 --- vstack

In [24]:
np.vstack((A,B))

array([[1, 1, 1],
       [2, 2, 2]])

+ 左右合并 --- hstack

In [25]:
np.hstack((A,B))

array([1, 1, 1, 2, 2, 2])

+ 不能简单的通过转置把  横向的序列  变成  竖向的矩阵

In [29]:
a=A.T
a

array([1, 1, 1])

In [30]:
a.shape

(3,)

+ 加入新的维度

In [35]:
a1=A[np.newaxis , : ]  # 横向加了一个维度
a2=A[ : , np.newaxis]  # 纵向加了一个维度
a1.shape, a2.shape

((1, 3), (3, 1))

In [36]:
a1,a2

(array([[1, 1, 1]]),
 array([[1],
        [1],
        [1]]))

In [37]:
b2=B[ : , np.newaxis]
np.hstack((a2,b2))

array([[1, 2],
       [1, 2],
       [1, 2]])