In [15]:
import numpy as np

In [16]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

+ 分割  split（矩阵，分割数，分割方向 1.竖切 0.横切）

In [17]:
np.split(A,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [18]:
np.split(A,3,axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

+ 不等量时候的分割 array_split(矩阵，分割数，分割方向 1.竖切 0.横切)

In [19]:
np.array_split(A,3,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

+ 分割  vsplit（矩阵，分割数） &  hsplit（矩阵，分割数）
# 注意
+ 好像是相反的

In [20]:
np.vsplit(A,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [21]:
np.hsplit(A,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]