In [15]:
import numpy as np

In [16]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [17]:
b=a
c=a
d=b

In [18]:
a[0]=11
a

array([11,  1,  2,  3])

+ a的改变会引起b、c、d同时发生改变---这就是numpy的赋值操作

In [19]:
b is a

True

In [20]:
b

array([11,  1,  2,  3])

In [21]:
c

array([11,  1,  2,  3])

In [22]:
d

array([11,  1,  2,  3])

+ 同样的，d的改变会引起a、b、c同时发生改变

In [23]:
d[1:3]=[22,33]

In [24]:
a

array([11, 22, 33,  3])

In [25]:
b

array([11, 22, 33,  3])

In [26]:
c

array([11, 22, 33,  3])

+ 如果你只想复制而不想关联--用copy()

In [28]:
a1=np.arange(4)
b1=a1.copy()
a1[0]=11

In [30]:
a1

array([11,  1,  2,  3])

In [31]:
b1

array([0, 1, 2, 3])